### ISSUE TITLE
Account Support

### ISSUE THREAD

**Issue by muhammadgholy** [CoinbaseWallet/CBHTTP#24]
Hello can you send any help to coinbase support about my account is restricted without any message, all my case is closed automatically, and i got no respond from twitter. what the hell is going on?

Latest Case # 06328620

**Comment by jaysonmald35** [comment]
Thanks

**Comment by InitialSupport** [comment]
> Hello can you send any help to coinbase support about my account is restricted without any message, all my case is closed automatically, and i got no respond from twitter. what the hell is going on?
> 
> Latest Case # 06328620

We'd be happy to look into this for you.
Kindly file a support ticket here
https://forms.gle/xABEcR5MwDBJAm1c6
